name: TablistCustomizer
version: '1.0.0'
main: me.anonlalani.tablistcustomizer.TablistCustomizer
api-version: '1.21'
author: AnonLaLaNI
description: Configurable tablist plugin with LuckPerms group support.
softdepend:
  - LuckPerms
  - PlaceholderAPI
commands:
  tablistcustomizer:
    description: Reloads TablistCustomizer config.
    aliases: [tlc, tabreload]
    usage: /tablistcustomizer reload
permissions:
  tablistcustomizer.reload:
    default: op
    description: Allows reloading TablistCustomizer.
